default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: postgres
  password: postgres
  database: flashcheker_development

test:
  <<: *default
  username: postgres
  password: postgres
  database: flashcheker_test

production:
  <<: *default
  # todo username
  # todo password
  database: flashcheker_production
